---
title: "Estadística 101"
output: html_document
---

## Capítulo 2: ¿Por qué importa tanto tanto la curva normal?

<!--<a href="https://www.youtube.com/playlist?list=PLzyW6TZJNgGYNH1thjd8KkRyr-JVPzvR3" target="_blank">Ver</a>-->

Contenido: 8 videos (1 hora 32 minutos en total)

#### Parte 1

<div class="video-responsive">
<iframe src="https://www.youtube.com/embed/IFNrCATEjxY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

<br/>

#### Parte 2

<div class="video-responsive">
<iframe src="https://www.youtube.com/embed/AdPw4jita2o" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

<br/>

#### Parte 3

<div class="video-responsive">
<iframe src="https://www.youtube.com/embed/kcxyC1b-QZM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

<br/>

#### Parte 4

<div class="video-responsive">
<iframe src="https://www.youtube.com/embed/zKnxXD9C-78" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

<br/>

#### Parte 5

<div class="video-responsive">
<iframe src="https://www.youtube.com/embed/BpH3_BJf5do" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

<br/>

#### Parte 6

<div class="video-responsive">
<iframe src="https://www.youtube.com/embed/SF4vsowPyrw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

<br/>

#### Parte 7

<div class="video-responsive">
<iframe src="https://www.youtube.com/embed/WPgwrvY8SEw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

<br/>

#### Parte 8

<div class="video-responsive">
<iframe src="https://www.youtube.com/embed/tHovt9mI7Xg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

<br/>

- ¿Por qué es importante graficar los datos?
- ¿Cómo se calcula la desviación estándar?
- ¿Qué es la suma de cuadrados (o suma de los errores al cuadrado)?

- ¿Cómo se puede visualizar la "forma" de los datos?
- ¿Qué características tiene la curva normal?
- ¿Cómo estimamos cuantas observaciones caen entre dos valores para una set de datos?
- ¿Qué porcentaje de los datos esta entre -1 SD y 1 SD?

- ¿Qué significa generalizar nuestros hallazgos?
- ¿Qué es la variación de la muestra (o sampling variation)?
- ¿Qué es el error estándar y como se calcula?
- ¿Qué son los intervalos de confianza?
- ¿Qué significa que cálculemos un promedio con un intervalo de confianza al 68%?
- ¿Qué significa que cálculemos un promedio con un intervalo de confianza al 95%?

<br/>
<br/>
