---
title: "Estadística 101"
output: html_document
---

## Capítulo 1a: ¿Para qué nos sirve la estadística?

<!--<a href="https://www.youtube.com/playlist?list=PLzyW6TZJNgGaCt1fDe0vl-pBt_Y4A0uaU" target="_blank">Ver</a>-->

Contenido: 4 videos (27 minutos en total)


#### Parte 1

<div class="video-responsive">
<iframe src="https://www.youtube.com/embed/10yOugyLLQg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

<br/>

#### Parte 2

<div class="video-responsive">
<iframe src="https://www.youtube.com/embed/ZHQsBt2xGkE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

<br/>

#### Parte 3

<div class="video-responsive">
<iframe src="https://www.youtube.com/embed/R6qDgUyJDJY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

<br/>

#### Parte 4

<div class="video-responsive">
<iframe src="https://www.youtube.com/embed/XiiWWa4VdqY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

<br/>

Preguntas clave:

- ¿Qué es la estadística descriptiva? ¿Qué es la estadística inferencial?
- ¿Qué es una población y una muestra? ¿Qué son los parámetros y los estadísticos?
- ¿Por qué necesitamos obtener una muestra para nuestros experimentos?
- ¿Por qué necesitamos las probabilidades para análisis estadísticos?

- ¿Que tipos de variables nos sirven para describir una muestra?
- ¿Que significa definir variables y operacionalizar?
- ¿Que es una variable independiente? ¿Que es una variable dependiente?
- ¿Cómo se construye una hipótesis?

- En un diseño experimental ¿qué es un factor?
- En un diseño experimental ¿qué es un nivel?
- ¿Cuál es la diferencia entre un diseño intra-sujetos y un diseño entre-sujetos?
- ¿Qué es un diseño experimental mixto?
- ¿Qué tipo de prueba se utiliza para comparar dos grupos experimentales?
- ¿Qué tipo de prueba se utiliza para comparar mas de dos grupos experimentales?

<br/>
<br/>
