---
title: "Estadística 101"
output: html_document
---

## Capítulo 6: ¿Y que hago después que calculo un ANOVA?

<!--<a href="https://www.youtube.com/playlist?list=PLzyW6TZJNgGZyMYhJtEN7PtT_a_ebC4nY" target="_blank">Ver</a>-->

Contenido: 3 videos (35 minutos en total)

#### Parte 1

<div class="video-responsive">
<iframe src="https://www.youtube.com/embed/nFcxN5qVYxY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

<br/>

#### Parte 2

<div class="video-responsive">
<iframe src="https://www.youtube.com/embed/z_jVSEKOVZM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

<br/>

#### Parte 3

<div class="video-responsive">
<iframe src="https://www.youtube.com/embed/qXR27qqjDvU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

<br/>

- ¿Que hago después de una prueba omnibus?
- ¿De qué depende el tipo de análisis que se hace después del ANOVA?
- ¿Qué significa que desglocemos la varianza explicada en los distintos contrastes en el análisis de contrastes planificados?
- ¿En un experimento dónde analizo el efecto de dos dosis de droga comparada con un placebo, que contrastes planificados se podrían hacer y que indican el intercepto y los betas de este modelo?
- ¿Por que es importante que el contraste que hagamos sea un contraste ortogonal?
- ¿Para que sirven los contrastes que evaluan una tendencia líneal o cuadrática?
- ¿Qué tipos de pruebas post-hoc existen?
- ¿Cuál es el riesgo que corremos si usamos una prueba post-hoc muy exigente (o conservadora)?
- ¿Cuál es el riesgo que corremos si usamos una prueba post-hoc poco exigente (o conservadora)?

<br/>
<br/>
