---
title: "Estadística 101"
output: html_document
---

## Capítulo 7: ¿Qué conceptos estadísticos debería manejar?

<a href="https://www.youtube.com/playlist?list=PLzyW6TZJNgGb_yYkeLqCSX0xz_0n1tu9z" target="_blank">Ver</a>

Contenido: 5 videos (46 minutos en total)

#### Parte 1

<div class="video-responsive">
<iframe src="https://www.youtube.com/embed/cOtuIWu9NQ0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

<br/>

#### Parte 2

<div class="video-responsive">
<iframe src="https://www.youtube.com/embed/dQ0LnqUAVnA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

<br/>

#### Parte 3

<div class="video-responsive">
<iframe src="https://www.youtube.com/embed/AbsXEad0gMQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

<br/>

#### Parte 4

<div class="video-responsive">
<iframe src="https://www.youtube.com/embed/Xh9-Mt2_WTE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

<br/>

#### Parte 5

<div class="video-responsive">
<iframe src="https://www.youtube.com/embed/bumW9zlQJdo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

<br/>

- ¿Qué me dice y qué no me dice el valor de p?
- ¿Cómo se interpreta un resultado estadístico nulo?
- ¿Cuál es la diferencia entre una hipótesis de una cola y una hipótesis de dos colas?
- ¿Por qué los criterios de significancia son más altos para una hipótesis de una cola que para una hipótesis de dos colas?
- ¿Qué es un error de tipo I?
- ¿Qué es un error de tipo II?
- ¿Por qué hay un balance entre el error de tipo I y II?
- ¿Qué es mas perjudicial para un estudio? ¿Un error de tipo I o II?
- ¿Qué es el tamaño del efecto?
- ¿Qué es el poder estadístico?
- ¿Qué podemos hacer para que en un proyecto de investigación tengamos las mejores posibilidades de encontrar un efecto que realmente existe?

<br/>
<br/>